// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var EncryptedEphemeralMessage = exports.EncryptedEphemeralMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineEncryptedEphemeralMessage()

function defineEncryptedEphemeralMessage () {
  var enc = [
    encodings.bytes
  ]

  EncryptedEphemeralMessage.encodingLength = encodingLength
  EncryptedEphemeralMessage.encode = encode
  EncryptedEphemeralMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.nonce)) throw new Error("nonce is required")
    var len = enc[0].encodingLength(obj.nonce)
    length += 1 + len
    if (!defined(obj.encryptedMessage)) throw new Error("encryptedMessage is required")
    var len = enc[0].encodingLength(obj.encryptedMessage)
    length += 1 + len
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.nonce)) throw new Error("nonce is required")
    buf[offset++] = 10
    enc[0].encode(obj.nonce, buf, offset)
    offset += enc[0].encode.bytes
    if (!defined(obj.encryptedMessage)) throw new Error("encryptedMessage is required")
    buf[offset++] = 18
    enc[0].encode(obj.encryptedMessage, buf, offset)
    offset += enc[0].encode.bytes
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      nonce: null,
      encryptedMessage: null
    }
    var found0 = false
    var found1 = false
    while (true) {
      if (end <= offset) {
        if (!found0 || !found1) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.nonce = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        case 2:
        obj.encryptedMessage = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found1 = true
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
